'use client'

import { useEffect, useState } from 'react'

import Head from 'next/head'
import useSWR from 'swr'
import axios from 'axios'
import styled from 'styled-components'

// Style
const HomeContainer = styled.div`
  max-width: 720px;
  margin: 0 auto;

  span {
    display: block;
    margin: 12px auto;
    padding: 12px 24px;
    font-weight: 600;
    width: max-content;
    background: #393939;
    color: #ffffff;
    border: 2px solid #393939;
    cursor: pointer;

    &:hover {
      background: #b49bd3;
      color: #393939;
      border: 2px solid #b49bd3;
    }
  }

  video {
    max-height: 100px;
    margin: 0 auto;
    display: block;
  }
`

const fetcher = (...args) => fetch(...args).then((res) => res.json())

export default function Home() {
  const { data: users, error } = useSWR('/api/users', fetcher)

  const userInfo = {
    userFullName: 'Isabel 3',
    userName: 'ica3',
    email: 'Isabelalbee+3@gmail.com ',
    password: 'password2',
  }

  console.log(users)

  const createUser = () => {
    // alert('hey quit it, thats not ready yet')
    axios.post(`/api/users/create`, { ...userInfo })
  }

  return (
    <HomeContainer>
      <Head>
        <title>HITLIST</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>HITLIST</h1>
      <p>Hey bubba just setting up the backend :)</p>

      {users &&
        users.map((user, i) => (
          <div key={i}>
            <p>name: {user.userFullName}</p>
            <p>email: {user.email}</p>
            <p>username: {user.userName}</p>
            <p>userId: {user._id}</p>
            <hr />
          </div>
        ))}

      <span onClick={createUser}>create user</span>
    </HomeContainer>
  )
}
