import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import styled from 'styled-components'

// Style
const HomeContainer = styled.div`
  max-width: 720px;
  margin: 0 auto;

  span {
    display: block;
    margin: 12px auto;
    padding: 12px 24px;
    font-weight: 600;
    width: max-content;
    background: #393939;
    color: #ffffff;
    border: 2px solid #393939;
    cursor: pointer;

    &:hover {
      background: #b49bd3;
      color: #393939;
      border: 2px solid #b49bd3;
    }
  }

  video {
    max-height: 100px;
    margin: 0 auto;
    display: block;
  }
`

export default function Home({ users }) {
  const userInfo = {
    userFullName: 'Isabel A',
    userName: 'ica',
    email: 'Isabelalbee@gmail.com ',
    password: 'password1',
  }

  const createUser = () => {
    alert('hey quit it, thats not ready yet')
    // axios.post(`/api/users/create`, { ...userInfo })
  }

  return (
    <HomeContainer>
      <Head>
        <title>HITLIST</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>HITLIST</h1>
      <p>Hey bubba just setting up the backend :)</p>

      {users.map((user, i) => (
        <div key={i}>
          <p>name: {user.userFullName}</p>
          <p>email: {user.email}</p>
          <p>username: {user.userName}</p>
          <hr />
        </div>
      ))}

      <span onClick={createUser}>create user</span>
    </HomeContainer>
  )
}

export async function getServerSideProps(ctx) {
  const users = await axios
    .get(`${process.env.API_BASE}/api/users`)
    .then((response) => response.data)

  return { props: { users } }
}
